### ISSUE TITLE
how do I leave comments on code?

### ISSUE THREAD

**Issue by rminnich** [l50/mass-wpscan#1]
do you have a way you're going to support PRs and all that jazz? 

Also it's worth it to set up travis, I can help, or see github.com/u-root/u-root/travis.yml and travis.sh

I have some suggestions but we ought to do them as PRs and use the hub tool and all that.

**Comment by l50** [comment]
I keep meaning to learn travis, so I suppose this a good time to finally get into that. I'll start looking into it, and if you have any recommendations on what I come up with, I'm all ears. 

As far as PRs go; if any come in, I'm happy to take them as they come. Hasn't come up yet in any of my projects, so this would be newer territory for me.

**Comment by l50** [comment]
Created my first travis build. Had to get some docker-compose action going to simplify building the test cases. Let me know what you think.
